### ISSUE TITLE
How can I select the hostname?

### ISSUE THREAD

**Issue by themightyoarfish** [SICKAG/sick_ldmrs_laser#14]
https://github.com/SICKAG/sick_ldmrs_laser/blob/1ff7e206df1599d3a1b393e2342258e480d6a5a5/sick_ldmrs_driver/src/sick_ldmrs_node.cpp#L558

This may be a stupid question, but is there any way to set the scanner's IP address without manually running `rosparam set /sick_ldmrs_node/hostname <IP>` before launching this node? It would be cool if params could be passed via the launch file, not only through `rosparam`and dynamic reconfigure. The respective definitions are commented out in the launch file, is there a reason for that?

**Comment by themightyoarfish** [comment]
A useful change would be to add an `<arg>` to the launch file which can be used to set the host name. Can submit PR if desired.

**Comment by mintar** [comment]
The launch file is only meant as an example, and the idea was that you simply copy it to your own config package and adjust it there. Of course we could add `<arg>`s for everything, but you can use `rosrun` directly instead.

So, instead of doing this: (which doesn't work because the launch file doesn't have args)

```bash
roslaunch sick_ldmrs_driver sick_ldmrs_node.launch hostname:=192.168.15.22
```

... you can do this:

```bash
rosrun sick_ldmrs_driver sick_ldmrs_node _hostname:=192.168.15.22
```

Please don't forget the `_` in front of the hostname. It's rosrun syntax for the parameter `~hostname`, where `~` stands for the node's private namespace.
