### ISSUE TITLE
Ground Plane Filtering

### ISSUE THREAD

**Issue by turtleMaster20** [SICKAG/sick_ldmrs_laser#20]
When I use the package, I see that the ground plane is being filtered.

Is this something that is being done by the ROS Package or does it exist much deeper?
Is it possible to remove this feature? I am trying to work with the information in the ground plane.

**Comment by mintar** [comment]
No, the ground plane is not being filtered. What happens is that the laser beams hit the ground at an acute angle, so only very little of the beam is being reflected back to the scanner. Therefore, the scanner cannot measure the distance to that point. Of course, this all depends on the properties of the surface.

You can see this effect if you go outside and scan a street surface. Usually there are no measurements for the asphalt, but there are measurements for the lane markers etc., because they are painted on in a highly reflective paint (at least here in Germany), so they reflect back enough light at the scanner even at an acute angle.

**Comment by turtleMaster20** [comment]
I tried to put some reflective material on the floor and tested it, but there are no reflections. I will try once again outside when the weather is a bit sunnier...For now I will close the issue.
